"""initial schema

Revision ID: 8d603b13adb3
Revises: 
Create Date: 2026-04-30 18:56:00.961499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d603b13adb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aerolineas',
    sa.Column('id_aerolinea', sa.Integer(), nullable=False),
    sa.Column('nombre_aerolinea', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_aerolinea', name=op.f('pk_aerolineas'))
    )
    op.create_table('aeropuertos',
    sa.Column('id_aeropuerto', sa.Integer(), nullable=False),
    sa.Column('nombre_aeropuerto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_aeropuerto', name=op.f('pk_aeropuertos'))
    )
    op.create_table('movimientos',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Enum('Salida', 'Llegada', name='tipo_movimiento'), nullable=False),
    sa.PrimaryKeyConstraint('id_movimiento', name=op.f('pk_movimientos')),
    sa.UniqueConstraint('descripcion', name=op.f('uq_movimientos_descripcion'))
    )
    op.create_table('vuelos',
    sa.Column('id_vuelo', sa.Integer(), nullable=False),
    sa.Column('id_aerolinea', sa.Integer(), nullable=False),
    sa.Column('id_aeropuerto', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_aerolinea'], ['aerolineas.id_aerolinea'], name=op.f('fk_vuelos_id_aerolinea_aerolineas')),
    sa.ForeignKeyConstraint(['id_aeropuerto'], ['aeropuertos.id_aeropuerto'], name=op.f('fk_vuelos_id_aeropuerto_aeropuertos')),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimientos.id_movimiento'], name=op.f('fk_vuelos_id_movimiento_movimientos')),
    sa.PrimaryKeyConstraint('id_vuelo', name=op.f('pk_vuelos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vuelos')
    op.drop_table('movimientos')
    op.drop_table('aeropuertos')
    op.drop_table('aerolineas')
    # Drop PG enum type explicitly: drop_table() does not cascade to it.
    sa.Enum(name='tipo_movimiento').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
